apiVersion: v1
kind: Service
metadata:
  name: hello-app-service
  labels:
    app: hello
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  # the port that this service should serve on.
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: hello